# See the documentation for more information:
# https://packit.dev/docs/configuration/

specfile_path: openscap-report.spec

# add or remove files that should be synced
files_to_sync:
    - .packit.yaml
    - src: plans/
      dest: plans/
    - src: .fmf/
      dest: .fmf/

# name in upstream package repository or registry (e.g. in PyPI)
upstream_package_name: openscap-report
# downstream (Fedora) RPM package name
downstream_package_name: openscap-report
# version tag template
upstream_tag_template: v{version}

srpm_build_deps:
  - python3-devel
  - python3-sphinx
  - python3-sphinx_rtd_theme
  - python3-jinja2
  - python3-lxml
  - redhat-display-fonts
  - redhat-text-fonts

actions:
  get-current-version:
    - python3 setup.py --version

jobs:
- job: propose_downstream
  trigger: release
  dist_git_branches:
    - fedora-rawhide
    - epel-8

- job: tests
  trigger: pull_request
  identifier: fedora-tests
  skip_build: true
  targets:
    - fedora-all

- job: tests
  trigger: pull_request
  identifier: epel-tests
  skip_build: true
  targets:
    - epel-9
    - epel-8

- job: copr_build
  trigger: pull_request
  identifier: fedora
  targets:
    - fedora-all

- job: copr_build
  trigger: pull_request
  identifier: epel9
  targets:
    - epel-9

- job: copr_build
  trigger: pull_request
  specfile_path: spec/rhel8/openscap-report.spec
  identifier: epel8
  targets:
    - epel-8
