name: package_dependency_test
on:
  push:
    branches: ["main", "*"]
  pull_request:
    branches: ["main"]
jobs:
  test-centos-stream-9:
    name: Test on CentOS Stream 9 (Container)
    runs-on: ubuntu-latest
    container:
      image: quay.io/centos/centos:stream9
    steps:
      - name: Install Deps
        run: dnf install -y python3-devel python3-setuptools rpm-build
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build
        run: python3 setup.py bdist_rpm --requires=python3-lxml,python3-jinja2 --build-requires=python3-devel,python3-setuptools
      - name: RPM install
        run: dnf install -y ./dist/openscap-report-*.noarch.rpm
      - name: Test parameter -h
        run: oscap-report -h
      - name: Test of the basic function
        working-directory: ./tests
        run: ./smoke.sh

  test-centos-stream-8:
    name: Test on CentOS Stream 8 (Container)
    runs-on: ubuntu-latest
    container:
      image: quay.io/centos/centos:stream8
    steps:
      - name: Install Deps
        run: dnf install -y python38 python38-devel python38-setuptools rpm-build
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build
        run: python3.8 setup.py bdist_rpm --requires=python38-lxml,python38-jinja2 --build-requires=python38-devel,python38-setuptools --python=python3.8
      - name: RPM install
        run: dnf install -y ./dist/openscap-report-*.noarch.rpm
      - name: Test parameter -h
        run: oscap-report -h
      - name: Test of the basic function
        working-directory: ./tests
        run: ./smoke.sh

  test-fedora-latest:
    name: Test on Fedora latest (Container)
    runs-on: ubuntu-latest
    container:
      image: fedora:latest
    steps:
      - name: Install Deps
        run: dnf install -y python3-devel python3-setuptools rpm-build
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build
        run: python3 setup.py bdist_rpm --requires=python3-lxml,python3-jinja2 --build-requires=python3-devel,python3-setuptools
      - name: RPM install
        run: dnf install -y ./dist/openscap-report-*.noarch.rpm
      - name: Test parameter -h
        run: oscap-report -h
      - name: Test of the basic function
        working-directory: ./tests
        run: ./smoke.sh

  test-fedora-rawhide:
    name: Test on Fedora Rawhide (Container)
    runs-on: ubuntu-latest
    container:
      image: fedora:rawhide
    steps:
      - name: Install Deps
        run: dnf install -y python3-devel python3-setuptools rpm-build
      - name: Fix missing Deps
        run: dnf install -y python3-devel python3-setuptools rpm-build
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build
        run: python3 setup.py bdist_rpm --requires=python3-lxml,python3-jinja2 --build-requires=python3-devel,python3-setuptools
      - name: RPM install
        run: dnf install -y ./dist/openscap-report-*.noarch.rpm
      - name: Test parameter -h
        run: oscap-report -h
      - name: Test of the basic function
        working-directory: ./tests
        run: ./smoke.sh
